# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvndrawC <- function(mu, sig) {
    .Call('_bvarsv_mvndrawC', PACKAGE = 'bvarsv', mu, sig)
}

carterkohn <- function(y, Z, Ht, Qt, m, p, t, B0, V0) {
    .Call('_bvarsv_carterkohn', PACKAGE = 'bvarsv', y, Z, Ht, Qt, m, p, t, B0, V0)
}

alphahelper <- function(y, Z, Btdraw) {
    .Call('_bvarsv_alphahelper', PACKAGE = 'bvarsv', y, Z, Btdraw)
}

sigmahelper1 <- function(Atdraw, M) {
    .Call('_bvarsv_sigmahelper1', PACKAGE = 'bvarsv', Atdraw, M)
}

sigmahelper2 <- function(capAt, yhat, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar) {
    .Call('_bvarsv_sigmahelper2', PACKAGE = 'bvarsv', capAt, yhat, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar)
}

sigmahelper3 <- function(capAt, sigt) {
    .Call('_bvarsv_sigmahelper3', PACKAGE = 'bvarsv', capAt, sigt)
}

getvc <- function(Ht) {
    .Call('_bvarsv_getvc', PACKAGE = 'bvarsv', Ht)
}

makeregs_fcC <- function(ydat, p) {
    .Call('_bvarsv_makeregs_fcC', PACKAGE = 'bvarsv', ydat, p)
}

mz <- function(n) {
    .Call('_bvarsv_mz', PACKAGE = 'bvarsv', n)
}

meye <- function(n) {
    .Call('_bvarsv_meye', PACKAGE = 'bvarsv', n)
}

vechC <- function(x) {
    .Call('_bvarsv_vechC', PACKAGE = 'bvarsv', x)
}

getfcsts <- function(Bt0, At0, Sigt0, Qdraw, Sdraw, Wdraw, ydat, nf, p) {
    .Call('_bvarsv_getfcsts', PACKAGE = 'bvarsv', Bt0, At0, Sigt0, Qdraw, Sdraw, Wdraw, ydat, nf, p)
}

wishdrawC <- function(h, n) {
    .Call('_bvarsv_wishdrawC', PACKAGE = 'bvarsv', h, n)
}

makeregs2_fcC <- function(dat, p) {
    .Call('_bvarsv_makeregs2_fcC', PACKAGE = 'bvarsv', dat, p)
}

matmult <- function(x, nt) {
    .Call('_bvarsv_matmult', PACKAGE = 'bvarsv', x, nt)
}

varfcst <- function(b, sig, y, nf) {
    .Call('_bvarsv_varfcst', PACKAGE = 'bvarsv', b, sig, y, nf)
}

